### ISSUE TITLE
no visualize_output.ipynb?

### ISSUE THREAD

**Issue by selipot** [philippemiron/marine-litter-caribbean#3]
I am not seeing the `notebooks/visualize_output.ipynb` notebook advertised in the `README.md` :)

**Comment by philippemiron** [comment]
It doesn't exist 🙈... Not sure why I put this in the Readme. Plus, Parcels switched to .zarr by default, and my code is using .nc so it would require some modifications (and I'm trying to wrap up the paper asap!).

**Comment by philippemiron** [comment]
It's included now.
